### ISSUE TITLE
Update to `v0.26` / backend fails with `v0.24`

### ISSUE THREAD

**Issue by pascalwengerter** [gleam-lang/developer-survey#8]
Just tried spinning up the repo, but it will fail with a backend error when using gleam `v0.24` (which is being used in the Dockerfile) and can't find the frontend app when using gleam `v0.26`.
Which makes me wonder if a) a very basic (integration) test setup and b) some sort of language version pinning (similar to e.g. the `"engines"` in a JS package.json) could help prevent such a situation?

**Comment by lpil** [comment]
Yup! There's an issue for this in the main repo!

Thanks for reporting the issue here

**Comment by pascalwengerter** [comment]
> Yup! There's an issue for this in the main repo!
> 
> Thanks for reporting the issue here, I'll upgrade this appp

You mean https://github.com/gleam-lang/gleam/issues/1813?
Could you give me some pointers as to what as to happen to update the survey to `v0.26`? Happy to work on that eventually

**Comment by lpil** [comment]
Ah yes! The directory structure for JavaScript changed very slightly. You'll need to find paths that have `.../dist/...` in them and remove that directory. so `abc/dist/efg` becomes `abc/efg`.
